[package]
name = "maat"
description = "The Maat programming language -- Rust-native syntax for writing zero-knowledge proofs"
keywords = ["compiler", "maat", "zero-knowledge", "zk", "cryptography"]
categories = ["compilers", "command-line-utilities"]
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"

[lib]
name = "maat"
path = "src/lib.rs"

[[bin]]
name = "maat"
path = "src/main.rs"

[dependencies]
ariadne = "0.6"
clap = { version = "4", features = ["derive"] }
rustyline = { version = "18", features = ["with-file-history", "derive"] }
serde_json = "1"

maat_span.workspace = true
maat_errors.workspace = true
maat_field.workspace = true
maat_lexer.workspace = true
maat_ast.workspace = true
maat_parser.workspace = true
maat_runtime.workspace = true
maat_types.workspace = true
maat_eval.workspace = true
maat_bytecode.workspace = true
maat_codegen.workspace = true
maat_vm.workspace = true
maat_trace.workspace = true
maat_air.workspace = true
maat_prover.workspace = true
maat_module.workspace = true
maat_stdlib.workspace = true

[dev-dependencies]
tempfile = "3"
