[package]
name = "maat_eval"
description = "Tree-walking interpreter and macro expansion engine for the Maat programming language"
keywords = ["compiler", "maat", "zero-knowledge", "zk", "interpreter"]
categories = ["compilers"]
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"

[dependencies]
indexmap.workspace = true

maat_errors.workspace = true
maat_ast.workspace = true
maat_field.workspace = true
maat_runtime.workspace = true
maat_span.workspace = true
