[package]
name = "maat_air"
description = "CPU constraint system (AIR) for the Maat programming language"
keywords = ["compiler", "maat", "zero-knowledge", "zk", "air"]
categories = ["compilers", "cryptography"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"

[dependencies]
maat_field.workspace = true
maat_bytecode.workspace = true
maat_trace.workspace = true

winter-air = "0.13"
